### ISSUE TITLE
QR 配网不支持 NB-IoT

### ISSUE THREAD

**Issue by JiyeHoo** [tuya/tuya-home-android-sdk-sample-java#1]

**Comment by JiyeHoo** [comment]
NB-IoT 设备按照 Tuya 的方案采用的是扫码配网的方式，我使用该 Demo 配置 NB-IoT 设备发现并不支持。
同时在开发手册中介绍的 NB-IoT 设备配网方式有误，使用通用接口按照文档的参数发现并不一致，我需要一个样例代码：https://developer.tuya.com/cn/docs/app-development/nb-device-activate?id=Kaixl5fvsvdwe#title-0-NB%E8%AE%BE%E5%A4%87%E9%85%8D%E7%BD%91

**Comment by TONGHUI97** [comment]
Demo提供的qrcode扫码配网支持的是联网设备，并不支持NB-Iot设备的配网。
需要支持NB设备的配网，可以：
1. 集成配网业务包，参考https://developer.tuya.com/cn/docs/app-development/deviceconfiguration?id=Ka8qhzk488zyd
2. 调用文档中的bind接口，传入uid即可。
3. 等待demo后续更新给出相应的配网方式。
