### ISSUE TITLE
Can't login to my account.

### ISSUE THREAD

**Issue by rogamaral** [tuya/tuya-home-android-sdk-sample-java#16]
Whenever I try to login I get the error: USER_PASSWD_WRONG

I double check the email and password and they are correct.

So, the problem may be the country code.
I use 351 for Portugal.
Is this correct?

**Comment by rogamaral** [comment]
Possibly the problem is not the country code as I tried all codes between 0 and 1000 without success.

Now, I don't know what could be wrong.

Any help is welcome.

Thanks.

Code used: 

```
public class MainActivity extends AppCompatActivity {

    private Button btLogin;

    private String strCountryCode = "0";
    private static final String strEmail = "xxxxx.xx.xxxxxx@gmail.com";
    private static final String strPassword = "xxxxxxxx";

    private int countryCode = 0;

...
...
...
    public void login(){

        btLogin.setText(strCountryCode);

        TuyaHomeSdk.getUserInstance().loginWithEmail(strCountryCode, strEmail, strPassword, new ILoginCallback() {
            @Override
            public void onSuccess(User user) {
                Toast.makeText(
                        MainActivity.this,
                        "Login OK: " + user.getEmail(),
                        Toast.LENGTH_LONG
                ).show();
            }

            @Override
            public void onError(String code, String error) {
                /*Toast.makeText(
                        MainActivity.this,
                        "Login Error: " + error,
                        Toast.LENGTH_LONG
                ).show();*/

                countryCode++;
                strCountryCode = "" + countryCode;

                if(countryCode <= 1000){
                    login();
                }
            }
        });
    }

    public void onLoginClick(View view) {
        login();
    }
....
....
}
```

**NOTE:**

AppKey and AppSecret are hard coded in AndroidManifest.xml
The t_s.bpm file is in the assets folder.

**Comment by rogamaral** [comment]
I found the reason for not being able to login:

Each account is linked to the application where it was created.

The account I'm trying to access was created with the SmartLife app.

**Comment by Innocencellh** [comment]
@rogamaral 
Thanks for your question. You are right ，each account is linked to the application where it was created.So you need to register a new account . Then login .

**Comment by AndreaLui** [comment]
What kind of account you have to use in order to login? There is a specific link for the account creation?
