### ISSUE TITLE
Not able to connect with Video doorbell with latest sdk

### ISSUE THREAD

**Issue by arihantdaga** [tuya/tuya-home-android-sdk-sample-java#21]
Using the home sdk: 3.29.6 and ipc sdk 3.31.5 . 
Not able to establish p2p connection.

**Comment by Innocencellh** [comment]
@arihantdaga thank u for your question .  Could u please provide details of the error logs ?

**Comment by arihantdaga** [comment]
It gives error code -10003 (timeout error)

**Comment by Innocencellh** [comment]
@arihantdaga Could u please provide the adblog ?
