### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by ganeshhv** [tuya/tuya-home-android-sdk-sample-java#34]
Invalid client; no access

**Comment by linhuiluo** [comment]
@ganeshhv plz check your project configuration ，You can refer to the documentation：https://developer.tuya.com/cn/docs/app-development/integrated?id=Ka69nt96cw0uj

**Comment by SilvanFem** [comment]
is there any documentation for IR devices

in panel sdk not getting IR device functionalities

**Comment by ganeshhv** [comment]
Is there any documentation about IR device,

Currently I'm working on the panel sdk but IR was not supporting in panel
sdk

I need to make own ui for that so if I use bizbundle

Both bizbundle and panel dependency than getting the same files error

So please hel me and suggest me how to handle and work on IR device
