### ISSUE TITLE
E/Tuya: tyble_BluetoothBondManager reflect bootstrap failed:null

### ISSUE THREAD

**Issue by hillanvieira** [tuya/tuya-home-android-sdk-sample-java#37]
I'm encountering a problem that I can't add bluetooth devices using the Smart Life Sdk.
the TuyaHomeSdk.getBleOperator().startLeScan function
returns nothing.
all permissions about bluetooth and location have been granted.
The device is a Lamp RGB BLE,This Sample code don't find the device.

In the Tuya Smart App available in play store the device works well, i can connect it manualy as ble lamp device.

Has anyone faced this problem?

**Comment by linhuiluo** [comment]
@hillanvieira We are very sorry, we suggest you move here to ask your question: https://service.console.tuya.com/8/3/create?step=4&id=01030408&source=suspension,to provide you with one-on-one guidance to match.
