### ISSUE TITLE
This project is using a legacy way to save files

### ISSUE THREAD

**Issue by wbspry** [tuya/tuya-home-android-sdk-sample-java#4]
This project is using a legacy way to storage movies and pictures.

https://github.com/tuya/tuya-home-android-sdk-sample-java/blob/63b2ac9e1ba5c08cb3ebe5482595dd5e0f16dbc0/homesdk-sample/ipc/src/main/AndroidManifest.xml#L11
This option will get ignored in this fall, when we have to update target api level to 30.

https://developer.android.com/training/data-storage/use-cases?hl=en

>Caution: After you update your app to target Android 11 (API level 30), the system ignores the requestLegacyExternalStorage attribute when your app is running on Android 11 devices, so your app must be ready to support scoped storage and to migrate app data for users on those devices.

Once we set the target api level above 29,
we no more can use legacy way to storage.

ex1)
https://github.com/tuya/tuya-home-android-sdk-sample-java/blob/63b2ac9e1ba5c08cb3ebe5482595dd5e0f16dbc0/homesdk-sample/ipc/src/main/java/com/tuya/smart/android/demo/camera/utils/Constants.java#L63
This type of using is not permitted above api level 29 and that results in causing an exception at this line below.
https://github.com/tuya/tuya-home-android-sdk-sample-java/blob/63b2ac9e1ba5c08cb3ebe5482595dd5e0f16dbc0/homesdk-sample/ipc/src/main/java/com/tuya/smart/android/demo/camera/utils/Constants.java#L67

ex2)
https://github.com/tuya/tuya-home-android-sdk/blob/2902aaf64df8e428996ae2da5188cde71afa6f12/TuyaSmartHomeSdkDemo/app/src/main/java/com/tuya/smart/android/demo/camera/CameraPanelActivity.java#L424
When I start ipc camera recording, this method always creates a blank file at a path like "/storage/emulated/0/Movies/xxxxxxxx.mp4".
Im not sure why this happens, but there is a possibility you are using some old way to save media files.

You can reproduce such problems with erasing the sentens "equestLegacyExternalStorage=true"  in AndroidManifest.xml.

**Comment by xiaoxuan-Tuya** [comment]
Hi,@wbspry 

Thanks for your feedback .As you said , the issue is caused by the new file-system policy after Android 10 .  But for the sake of transition, we provides `requestLegacyExternalStorage` mechanism to help the sample using the original mechanism  to read and write file to memory card. We will upgrade the sample within this month and you could follow up this project.

**Comment by wbspry** [comment]
Thank you. Take your time.

**Comment by xiaoxuan-Tuya** [comment]
Happy coding :)
