### ISSUE TITLE
Can we get a Flutter supporting sdk for all your amazing services?

### ISSUE THREAD

**Issue by Hippopop** [tuya/tuya-home-android-sdk-sample-java#41]
Currently, we're converting a native app that includes one of your SDKs to Flutter. So far we can't see any supporting implementation that we can directly use inside a flutter app. We're just curious if we'll see any flutter adaptation for your services, as flutter is now one of the most used cross-platform software development tools.

Thank you!

**Comment by xionghai123** [comment]
Sorry, now we don't have an SDK implemented by flutter yet. For this, you can implement a layer of flutter plugin based on the current Java SDK.

**Comment by xionghai123** [comment]
> Currently, we're converting a native app that includes one of your SDKs to Flutter. So far we can't see any supporting implementation that we can directly use inside a flutter app. We're just curious if we'll see any flutter adaptation for your services, as flutter is now one of the most used cross-platform software development tools.
> 
> Thank you!

Sorry, we don't have an SDK implemented by flutter yet. For this, you need to implement a layer of flutter plugin based on the current Java SDK.
