### ISSUE TITLE
Can't startup

### ISSUE THREAD

**Issue by Samhenz** [tuya/tuya-home-android-sdk-sample-java#42]
I'm trying to debug the apk file and run it in my android phone but the app keeps in the launching screen and never startup. How can I solved it?

**Comment by taojingGino** [comment]
You can create ticket here, describe the detail of the problem, and we will answer the question there

https://service.console.tuya.com/8/3/create?source=help_sidebar

**Comment by taojingGino** [comment]
> I'm trying to debug the apk file and run it in my android phone but the app keeps in the launching screen and never startup. How can I solved it?

You can create ticket here, describe the detail of the problem, and we will answer the question there

https://service.console.tuya.com/8/3/create?source=help_sidebar
