### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by ... /lib/arm64/libfolly_runtime.so"...

### ISSUE THREAD

**Issue by tobynnt** [tuya/tuya-home-android-sdk-sample-java#48]
Hello, after I upgraded the SDK to latest version as required from tuyasmart:4.0.5 to thingsmart:5.0.1, then I got the following error:

**java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~rtyOTslZIRFldhmxSvxvuQ==/com.tuyasmartlifedemo-_cmITKituaNb51YhR_kRBA==/lib/arm64/libfolly_runtime.so"... result: 0**
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1127)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:943)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:855)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:802)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:772)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:24)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:369)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:316)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:94)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.tuyasmartlifedemo.MainApplication.onCreate(MainApplication.java:63)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1285)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7214)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:240)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:351)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8364)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
04-21 20:36:18.003 21376 21376 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

![error_smartlifev5](https://user-images.githubusercontent.com/130066197/233650702-c55a6f87-5aca-4e4c-bbd3-b3938195f59b.png)

I also set up my project as the docs:

android {
   defaultConfig {
      ndk {
         abiFilters "armeabi-v7a", "arm64-v8a"
      }
   }
   packagingOptions {
      pickFirst 'lib/*/libc++_shared.so' // An Android Archive (AAR) file contains an Android library. If the .so file exists in multiple AAR files, select the first AAR file.
   }
}
dependencies {
   implementation fileTree(dir: 'libs', include: ['*.aar'])
   implementation 'com.alibaba:fastjson:1.1.67.android'
   implementation 'com.squareup.okhttp3:okhttp-urlconnection:3.14.9'

   // The latest stable App SDK for Android.
   implementation 'com.facebook.soloader:soloader:0.10.4+'
   implementation 'com.thingclips.smart:thingsmart:5.0.1'
}

Do you have any solution for this problem? Btw, the project can run when **I remove this line "implementation fileTree(dir: 'libs', include: ['*.aar'])"**

Thanks alot for your help!

**Comment by linhuiluo** [comment]
@tobynnt Thank you for your feedback.You have to check if the integration is correct first, you can refer to the following document : https://developer.tuya.com/en/docs/app-development/integrated?id=Ka69nt96cw0uj#title-3-%E7%AC%AC%E4%B8%80%E6%AD%A5%EF%BC%9A%E5%88%9B%E5%BB%BA%20Android%20%E5%B7%A5%E7%A8%8B .It is important to note that you need to set the **applicationId** correctly and remove the security from your project.The most important thing is that the libhermes.so so file is not our.

**Comment by keilaiendraicak** [comment]
Did you find any solution to this?

**Comment by Daynnnnn** [comment]
Also struggling with this, anyone found anything?

**Comment by foyst** [comment]
For anyone else struggling with this, we found this is caused by an older version of `libc++_shared.so` being bundled in the `security-algorithm-1.0.0.aar` file. This was conflicting with the version of this provided by RN, causing the above error.

We managed to remove this library by:

- Changing the file extension from `.aar` to `.zip`, then extracting the archive
- Removing `jni/arm64-v8a/libc++_shared.so` and `jni/armeabi-v7a/libc++_shared.so`
- Repackaging the archive using ` jar cvf security-algorithm-1.0.0.aar -C security-algorithm-1.0.0/ .`

Hope this helps!

**Comment by skyz1** [comment]
> For anyone else struggling with this, we found this is caused by an older version of `libc++_shared.so` being bundled in the `security-algorithm-1.0.0.aar` file. This was conflicting with the version of this provided by RN, causing the above error.
> 
> We managed to remove this library by:
> 
> * Changing the file extension from `.aar` to `.zip`, then extracting the archive
> * Removing `jni/arm64-v8a/libc++_shared.so` and `jni/armeabi-v7a/libc++_shared.so`
> * Repackaging the archive using ` jar cvf security-algorithm-1.0.0.aar -C security-algorithm-1.0.0/ .`
> 
> Hope this helps!

Wow, this actually worked. Many hours wasted due to this issue...
