### ISSUE TITLE
运行SDK demo报错

### ISSUE THREAD

**Issue by bingely** [tuya/tuya-home-android-sdk-sample-java#51]
Execution failed for task ':ipc:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':ipc:debugRuntimeClasspath'.
   > Could not find com.thingclips.smart:thingsmart-modularCampAnno:1.0.0-SNAPSHOT.
     Searched in the following locations:
       - file:/E:/xhrj_project/TuYa/tuya-home-android-sdk-sample-kotlin/homesdk_sample/ipc/https : /dl.bintray.com/jenly/maven /com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/maven-metadata.xml
       - file:/E:/xhrj_project/TuYa/tuya-home-android-sdk-sample-kotlin/homesdk_sample/ipc/https : /dl.bintray.com/jenly/maven /com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/thingsmart-modularCampAnno-1.0.0-SNAPSHOT.pom
     Required by:
         project :ipc > project :base_res > com.thingclips.smart:thingsmart:5.1.0 > com.thingclips.smart:thingsmart-device-core:5.1.0 > com.thingclips.smart:thingsmart-asynclib:5.1.0-rc.3

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by MRwangqi** [comment]
@bingely  under global exclusion：

https://github.com/tuya/tuya-home-android-sdk-sample-java/blob/main/homesdk-sample/app/build.gradle#L56-L58

**Comment by bingely** [comment]
是加了这个才可以吗，我加了和去掉都是报错

**Comment by MRwangqi** [comment]
@bingely 需要加这段代码，全局把这个依赖给排除就可以了，这个示例 demo 刚下载跑了下，可以编译成功
