### ISSUE TITLE
"libthing_security_algorithm.so" not found

### ISSUE THREAD

**Issue by qingfeng-zhang** [tuya/tuya-home-android-sdk-sample-java#54]
when I tried to run app, there have some errors  :java.lang.UnsatisfiedLinkError: dlopen failed: library "libthing_security_algorithm.so" not found , anyboby can help me  where is wrong?

**Comment by taojingGino** [comment]
https://developer.tuya.com/cn/docs/app-development/integrated?id=Ka69nt96cw0uj#title-5-%E7%AC%AC%E4%B8%89%E6%AD%A5%EF%BC%9A%E9%9B%86%E6%88%90%E5%AE%89%E5%85%A8%E7%BB%84%E4%BB%B6

@qingfeng-zhang pls check this doc

**Comment by qingfeng-zhang** [comment]
thanks, it worked

**Comment by zlinoliver** [comment]
@qingfeng-zhang thanks for your feedbacks, as the issue is resolved, will close it now.
