### ISSUE TITLE
 Business apiName: smartlife.m.user.mobile.register  errorMsg:Invalid client;No access

### ISSUE THREAD

**Issue by qingfeng-zhang** [tuya/tuya-home-android-sdk-sample-java#55]
when I tryied to register or login by my tuya account ,  there have one error message: 

D/Thing: Business api: smartlife.m.user.mobile.register ，293 ms，
E/Thing: Business apiName: smartlife.m.user.mobile.register  errorMsg:Invalid client;No access

I have configured  my signature information :
signingConfigs {
        debug {
            storeFile file('../tuya.jks')
            storePassword '1234567899'
            keyAlias 'key0'
            keyPassword '12345678'
        }
        release {
            storeFile file('../tuya.jks')
            storePassword '1234567899'
            keyAlias 'key0'
            keyPassword '12345678'
        }
    }

may I  know why have such error?

**Comment by taojingGino** [comment]
https://developer.tuya.com/cn/docs/app-development/integrated?id=Ka69nt96cw0uj#title-5-%E7%AC%AC%E4%B8%89%E6%AD%A5%EF%BC%9A%E9%9B%86%E6%88%90%E5%AE%89%E5%85%A8%E7%BB%84%E4%BB%B6

@qingfeng-zhang pls check this doc, this error means your Appkey, AppSecret and certificate signatures do not match

**Comment by DouglasNovaki** [comment]
@qingfeng-zhang  try this

https://github.com/tuya/tuya-home-android-sdk-sample-java/pulls#:~:text=Added%20implementation%20to%20retrieve%20JAR%20and%20AAR%20files%20from%20the%20%27libs%27%20directory.

**Comment by qingfeng-zhang** [comment]
but I  already added :
 implementation fileTree(include: ['*.aar'], dir: 'libs')
inside app\build.gradle

**Comment by taojingGino** [comment]
<img width="943" alt="ba865152-d9e8-4f4c-8b29-1b627cd2c52b" src="https://github.com/tuya/tuya-home-android-sdk-sample-java/assets/59640671/fa7fe18c-761c-446d-acb8-6dc855667aad">
did copy the file in you project

 i think you should check the docment step again @qingfeng-zhang 
 https://developer.tuya.com/cn/docs/app-development/integrated?id=Ka69nt96cw0uj#title-5-%E7%AC%AC%E4%B8%89%E6%AD%A5%EF%BC%9A%E9%9B%86%E6%88%90%E5%AE%89%E5%85%A8%E7%BB%84%E4%BB%B6

**Comment by zlinoliver** [comment]
As we haven't received any updates for the suggested solutions from your side for 5 days, will close this issue for now. You can reopen it if you have any further questions. Thanks for your feedbacks! @qingfeng-zhang
