### ISSUE TITLE
thingMapping.gradle is not compatible with Gradle 8.x

### ISSUE THREAD

**Issue by 0speedy** [tuya/tuya-home-android-sdk-sample-java#59]
You're using gradle version 4.4.1 which is almost 7 years old. Your `thingMapping.gradle` doesn't work with gradle 8.x for example.

Can you please provide a version compatible with gradle 8.x?

**Comment by MRwangqi** [comment]
Can you provide an error report that gradle 8.x is not supported? @0speedy

**Comment by taojingGino** [comment]
I will close this issue. If there are any issues, you can continue to provide feedback

**Comment by 0speedy** [comment]
Sorry for the late response - I'm getting an error "Gradle DSL method not found" for all methods defined in that gradle file. I'm on Gradle 8.2.1.
