### ISSUE TITLE
Compatible with react-native 0.73.6

### ISSUE THREAD

**Issue by dokienkkk** [tuya/tuya-home-android-sdk-sample-java#60]
Hi team, I created a new project using react-native version 0.73.6 and integrated the SDK according to the instructions at https://developer.tuya.com/en/docs/app-development/integrated?id=Ka69nt96cw0uj
The first launch everything was OK but I crashed the app after rebuilding
Here is the log:
![Screenshot 2024-03-16 at 18 19 15](https://github.com/tuya/tuya-home-android-sdk-sample-java/assets/74960394/f5cc3bde-659a-4b8b-9c80-aa043691d2ed)

**Comment by dokienkkk** [comment]
I tested my project with tuya sdk v4 and everything works fine. I think the problem is related to the security-algorithm-1.0.0-beta.aar file in v5

**Comment by xionghai123** [comment]
Could you please provide a list of the Graffiti SDKs currently integrated, so I can print out the dependency tree to review?

> I tested my project with tuya sdk v4 and everything works fine. I think the problem is related to the security-algorithm-1.0.0-beta.aar file in v5

**Comment by xionghai123** [comment]
> I tested my project with tuya sdk v4 and everything works fine. I think the problem is related to the security-algorithm-1.0.0-beta.aar file in v5

Could you please provide a list of the tuya SDKs currently integrated, so I can print out the dependency tree to review?

**Comment by dokienkkk** [comment]
> > I tested my project with tuya sdk v4 and everything works fine. I think the problem is related to the security-algorithm-1.0.0-beta.aar file in v5
> 
> Could you please provide a list of the tuya SDKs currently integrated, so I can print out the dependency tree to review?

yes. this is my dependencies:
```java
dependencies {
    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")
    implementation("com.facebook.react:flipper-integration")

    implementation fileTree(dir: 'libs', include: ['*.aar'])
    implementation 'com.alibaba:fastjson:1.1.67.android'
    implementation 'com.squareup.okhttp3:okhttp-urlconnection:3.14.9'

    // The latest stable App SDK for Android.
    implementation 'com.facebook.soloader:soloader:0.11.0+'
    implementation 'com.thingclips.smart:thingsmart:5.8.1'

    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}
```

**Comment by taojingGino** [comment]
@dokienkkk Received, we will fix this issue in future versions

**Comment by taojingGino** [comment]
@dokienkkk You can also try

Macos or Linux can use the zip command to delete files within:

#Remove libc++_shared.so from aar
Zip - d security algorithm-1.0.0.aar jni/arm64-v8a/libc++_shared.so jni/armeabi-v7a/libc++_shared.so

Windows can decompress aar, delete so, recompress the zip file, and rename it to security algorithm-1.0.0.aar

This method can remove so from aar, but we have multiple components that contain libc++_shared.so
You need to place the libc++_shared. so of ndk26 in your own project to ensure that the final version of the app for packaging is a higher version so
