### ISSUE TITLE
Fatal Exception: java.lang.SecurityException

### ISSUE THREAD

**Issue by hetsgandhi** [tuya/tuya-home-android-sdk-sample-java#61]
Fatal Exception: java.lang.SecurityException
com.alen.air: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

com.thingclips.sdk.blelib.utils.BluetoothUtils.registerGlobalReceiver (BluetoothUtils.java:1)
com.thingclips.sdk.blelib.utils.BluetoothUtils.registerReceiver (BluetoothUtils.java:1)
com.thingclips.sdk.blelib.receiver.BluetoothReceiver.<init> (BluetoothReceiver.java:31)
com.thingclips.sdk.blelib.receiver.BluetoothReceiver.getInstance (BluetoothReceiver.java:4)
com.thingclips.sdk.blelib.BluetoothClientImpl.registerBluetoothReceiver (BluetoothClientImpl.java:2)
com.thingclips.sdk.blelib.BluetoothClientImpl.handleMessage (BluetoothClientImpl.java:6)

**Comment by hackill** [comment]
从错误上看 是android 14的广播适配问题。demo中还是5.1.0的版本，可以替换成官网上的最新版本 

Based on the error, it seems to be an issue with adapting broadcasts for Android 14. The demo is still using version 5.1.0, which can be replaced with the latest version from the official website.
