### ISSUE TITLE
Business apiName: smartlife.m.user.mobile.register errorMsg:Invalid client;No access

### ISSUE THREAD

**Issue by wallacerenan** [tuya/tuya-home-android-sdk-sample-java#63]
I'm testing the template:
https://github.com/tuya/tuya-home-android-sdk-sample-java

and I'm getting an error: Business apiName: smartlife.m.user.mobile.register errorMsg:Invalid client;No access

**Comment by wallacerenan** [comment]
![image](https://github.com/tuya/tuya-home-android-sdk-sample-java/assets/79864236/98cbeaef-9411-4f3f-a60b-f2f958c9f6e1)


![image](https://github.com/tuya/tuya-home-android-sdk-sample-java/assets/79864236/41485be2-1ea4-4f70-851a-388e94265cd0)

![image](https://github.com/tuya/tuya-home-android-sdk-sample-java/assets/79864236/a33545fa-c365-4b26-9a4d-53d680f975e2)

![image](https://github.com/tuya/tuya-home-android-sdk-sample-java/assets/79864236/d2228ffb-46fc-4227-a2bb-5c5eb36f516c)

![image](https://github.com/tuya/tuya-home-android-sdk-sample-java/assets/79864236/5d147456-1811-4d32-b2c6-0a8ce3c0d83f)

**Comment by taojingGino** [comment]
Invalid client；No access.This means your packageName, AppKey, AppSecret, and certificate signature mismatch.
check this doc
https://developer.tuya.com/en/docs/app-development/integrated?id=Ka69nt96cw0uj#title-6-Step%204%3A%20Configure%20AppKey%2C%20AppSecret%2C%20and%20certificate%20signature
@wallacerenan
