### ISSUE TITLE
Not adding device in android 

### ISSUE THREAD

**Issue by phantom-j** [tuya/tuya-home-android-sdk-sample-java#64]
I am using Android sdk 5.14 ,i can signup& signin .

While adding device finding device is happening ,adding progress also its showing.
 Iam getting device bean,localkey,device details.

But after the process if i check home bean device list showing null.
Its not adding devices to device list hence i cant control also.

**Comment by taojingGino** [comment]
try get home bean again
ThingHomeSdk.newHomeInstance(homeId).getHomeDetail(new IThingHomeResultCallback() {
	@Override
	public void onSuccess(HomeBean homeBean) {

	}

	@Override
	public void onError(String errorCode, String errorMsg) {

	}
});
or you can try get home list again and than get homeBean
ThingHomeSdk.getHomeManagerInstance().queryHomeList(new IThingGetHomeListCallback() {
	@Override
	public void onSuccess(List<HomeBean> homeBeans) {
		// do something
	}
	@Override
	public void onError(String errorCode, String error) {
		// do something
	}
});      
@phantom-j
