### ISSUE TITLE
运行demo。

### ISSUE THREAD

**Issue by 2054765176** [tuya/tuya-home-android-sdk-sample-java#65]
下载完demo后需要进行哪些集成操作。
1.在快速集成安卓app sdk网站链接中，implementation 'com.thingclips.smart:thingsmart:5.15.0'，这里是5.15.0版本，在创建APP SDK下载构造得到的依赖版本为5.14.0，应该以哪个版本为标准。
2.demo里面根目录的build.gradle添加maven仓库地址后， classpath "com.android.tools.build:gradle:4.1.1"，这个地方的版本由什么决定，一定要4.1.1版本吗。
3.app的build.gradle里面的minsdkversion改为23，targetsdkversion改为34，其它模块如ipc、ble_lock等的buidl.gradle里面的minsdkversion改为23，targetsdkversion改为34吗？

在下载完demo并按照所说的步骤完成集成后，在构建同步过程中和run app过程中都出现了各种报错，想知道下载完demo应该在哪些地方改哪些地方不改才能避免运行报错。使用的gradle版本，agp版本和jdk版本都有什么具体要求吗。

**Comment by MRwangqi** [comment]
@2054765176 可以参考论坛帖子 https://www.tuyaos.com/viewtopic.php?t=3682
