### ISSUE TITLE
BT3L蓝牙单连方案，绑定后可以检查到设备在线，当退出应用再重新进入之后无法检测到设备在线的状态，一直显示离线。

### ISSUE THREAD

**Issue by demoCrash** [tuya/tuya-home-android-sdk-sample-java#9]

**Comment by Innocencellh** [comment]
您好，这边按您说的路径操作后并没有发现您所说的问题，sample里设备的离线/在线状态取的是DeviceBean里的isOnline字段，这个字段表示云端或者本地在线，其中一个满足就是在线状态，DeviceBean里面还有个isLocalOnline的字段，您可以自行试下，这个字段是表示本地在线，比如单点蓝牙。

**Comment by demoCrash** [comment]
特意录个视频，看一下问题在哪里。
这个视频演示绑定和显示设备状态。很明显不显示在线。一直离线

https://user-images.githubusercontent.com/7745333/125016578-2a11cc80-e0a4-11eb-9c60-afb91b9463a2.mp4

这个视频对比测试，表示我设备是可以显示状态的，因为你官方的app是显示正常的。操作方式，从ty sdk中将设备移除，用官方app测试绑定和显示状态。

https://user-images.githubusercontent.com/7745333/125016664-457cd780-e0a4-11eb-8319-1da890ce6de0.mp4

**Comment by radishwu** [comment]
好的，谢谢反馈，我们将会在近段时间修复sample问题。

**Comment by demoCrash** [comment]
我已经创建工单解决这个问题了。
